# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
baseURL = "https://anjackson.net/"
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
paginate = 10
summaryLength = 0

buildDrafts = false
buildFuture = false

# googleAnalytics = "G-XXXXXXXXX"

[permalinks]
  [permalinks.page]
    blog = '/:year/:month/:day/:slug/'
    digipres-lessons-learned = '/:year/:month/:day/:slug/'
    building-web-archives = '/:year/:month/:day/:slug/'
    tutorials = '/training/:slug/'
  [permalinks.section]
    blog = '/blog/'
    tutorials = '/training/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe= true

[outputFormats]
    [outputFormats.RSS]
        baseName = "feed" # Support feed.xml instead of index.xml to maintain Jekyll links

[services]
  [services.rss]
    limit = 500 # Limit the depth of RSS feeds so they're not _infinite_.

[frontmatter]
  date = [':filename', ':default', 'created']
  lastmod = ['lastmod', ':git', ':default', 'changed']

# Allow access to the CONTEXT Netlify environment variable:
# https://docs.netlify.com/configure-builds/environment-variables/#build-metadata
[security.funcs]
getenv = ['^HUGO_', '^CONTEXT$' ]

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
