backend:
  name: git-gateway
  repo: anjackson/anjackson.github.io
  branch: master
  
# Use the editorial workflow, for working on long posts:
#publish_mode: editorial_workflow

media_folder: assets/images/uploads
public_folder: /assets/images/uploads

collections:
- name: "main-blog"
  label: "General Blog Post"
  folder: _posts
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  preview_path: "{{year}}/{{month}}/{{day}}/{{title}}"
  preview_path_date_field: "date"
  fields:
  - {label: 'Title', name: 'title', widget: 'string'}
  - {label: 'Sub-title', name: 'subtitle', widget: 'string'}
  - {label: 'Date', name: 'date', widget: 'date'}
  - {label: 'Blog series', name: 'category', widget: 'select', options: ["building-web-archives","mining-web-archives", "defunct-formats"], required: false}
  - {label: 'Tags', name: 'tags', widget: 'select', options: ["Websites", "Reports", "Web Archives", "Digital Preservation", "Data Mining"], multiple: true, required: false}
  - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
  - {label: "Author", name: "author", widget: "hidden", default: "anj"}
  - {label: "Show in homepage/feeds", name: "shown", widget: "boolean", default: true}
  - {label: 'Body', name: 'body', widget: 'markdown'}
