backend:
  name: git-gateway
  repo: anjackson/anjackson.github.io
  branch: master

media_folder: assets/images/uploads
public_folder: /assets/images/uploads

collections:
- name: "main-blog"
  label: "General Blog Posts"
  folder: _posts
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  preview_path: "blog/{{slug}}"
  fields:
  - {label: 'Title', name: 'title', widget: 'string'}
  - {label: 'Sub-title', name: 'subtitle', widget: 'string'}
  - {label: 'Category', name: 'category', widget: 'select', options: ["mining-web-archives"]}
  - {label: 'Tags', name: 'tags', widget: 'select', options: ["Websites"], multiple: true}
  - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
  - {label: "Author", name: "author", widget: "hidden", default: "anj"}
  - {label: "Shown", name: "author", widget: "boolean", default: true}
  - {label: 'Body', name: 'body', widget: 'markdown'}
